"""loan disbursement link

Revision ID: 0e834d77d779
Revises: 0a55d0cf8027
Create Date: 2026-09-02 06:15:53.082228
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e834d77d779'
down_revision: Union[str, None] = '0a55d0cf8027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('disbursement_transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loan', 'transaction', ['disbursement_transaction_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.drop_column('loan', 'disbursement_transaction_id')
    # ### end Alembic commands ###
