"""brsapi provider, price alerts, manual income

Revision ID: 323c95366e99
Revises: 60d4bc6f0d38
Create Date: 2026-09-04 14:49:40.674054
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '323c95366e99'
down_revision: Union[str, None] = '60d4bc6f0d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('threshold_rial', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_price_rial', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_code'], ['market_item.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alert_item_code'), 'price_alert', ['item_code'], unique=False)
    op.add_column('price_point', sa.Column('change_percent', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('transaction', sa.Column('is_income', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_transaction_is_income'), 'transaction', ['is_income'], unique=False)

    conn = op.get_bind()

    # ---- تعیین تکلیف درآمدهای موجود ----
    # تا حالا هر واریزی «درآمد» شمرده می‌شد. حالا فقط چیزی درآمد است که
    # کاربر تأیید کرده باشد. برای اینکه از صفر شروع نکند، دسته‌هایی که
    # معنایشان روشن است خودکار تعیین‌تکلیف می‌شوند و بقیه بلاتکلیف
    # می‌مانند تا خودش تصمیم بگیرد.
    conn.execute(sa.text("""
        UPDATE transaction t SET is_income = true
        FROM category c
        WHERE c.id = t.category_id
          AND t.amount_rial > 0
          AND c.slug IN ('salary', 'bank_interest', 'refund', 'other_income')
    """))

    # تعدیل و اصلاح سند درآمد نیست — برگشتِ چیزی است که قبلاً خرج شده
    conn.execute(sa.text("""
        UPDATE transaction t SET is_income = false
        FROM category c
        WHERE c.id = t.category_id
          AND t.amount_rial > 0
          AND c.slug = 'adjustment'
    """))

    # انتقال بین حساب‌های خودم و حواله‌های برگشتی هرگز درآمد نیستند
    conn.execute(sa.text("""
        UPDATE transaction SET is_income = false
        WHERE amount_rial > 0 AND (is_self_transfer OR is_reversed)
    """))

    # ---- پاک‌سازی اقلام بازار ----
    # سرویس تازه (BrsApi) نمادهای دیگری دارد و کاربر سکه و طلای آب‌شده و
    # درهم را نمی‌خواهد. قیمت‌های قدیمی به نمادهای منسوخ تعلق دارند.
    conn.execute(sa.text("DELETE FROM price_point"))
    conn.execute(sa.text("DELETE FROM asset_holding"))
    conn.execute(sa.text("DELETE FROM market_item"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_is_income'), table_name='transaction')
    op.drop_column('transaction', 'is_income')
    op.drop_column('price_point', 'change_percent')
    op.drop_index(op.f('ix_price_alert_item_code'), table_name='price_alert')
    op.drop_table('price_alert')
    # ### end Alembic commands ###
