"""tx links: cross-account, reversal, fee

Revision ID: 4434d11c5116
Revises: 47ca64e05c18
Create Date: 2026-09-02 05:49:41.444164
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4434d11c5116'
down_revision: Union[str, None] = '47ca64e05c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tx_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('primary_tx_id', sa.Integer(), nullable=False),
    sa.Column('secondary_tx_id', sa.Integer(), nullable=False),
    sa.Column('amount_rial', sa.BigInteger(), nullable=False),
    sa.Column('seconds_apart', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('matched_by', sa.String(length=120), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_rejected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_tx_id'], ['transaction.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secondary_tx_id'], ['transaction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'primary_tx_id', 'secondary_tx_id', name='uq_tx_link')
    )
    op.create_index(op.f('ix_tx_link_kind'), 'tx_link', ['kind'], unique=False)
    op.create_index(op.f('ix_tx_link_primary_tx_id'), 'tx_link', ['primary_tx_id'], unique=False)
    op.create_index(op.f('ix_tx_link_secondary_tx_id'), 'tx_link', ['secondary_tx_id'], unique=False)
    # server_default لازم است چون سطرهای موجود مقدار ندارند
    op.add_column(
        'transaction',
        sa.Column('is_reversed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index(op.f('ix_transaction_is_reversed'), 'transaction', ['is_reversed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_is_reversed'), table_name='transaction')
    op.drop_column('transaction', 'is_reversed')
    op.drop_index(op.f('ix_tx_link_secondary_tx_id'), table_name='tx_link')
    op.drop_index(op.f('ix_tx_link_primary_tx_id'), table_name='tx_link')
    op.drop_index(op.f('ix_tx_link_kind'), table_name='tx_link')
    op.drop_table('tx_link')
    # ### end Alembic commands ###
