"""melli importer: self-declared flag

Revision ID: 47ca64e05c18
Revises: 59da7f106ad5
Create Date: 2026-09-02 05:42:21.575513
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47ca64e05c18'
down_revision: Union[str, None] = '59da7f106ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default لازم است چون سطرهای موجود مقدار ندارند
    op.add_column(
        'transaction',
        sa.Column('is_self_declared', sa.Boolean(), nullable=False,
                  server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'is_self_declared')
    # ### end Alembic commands ###
