"""wishlist and debt source account

Revision ID: 4ee7c13db44c
Revises: 323c95366e99
Create Date: 2026-09-04 20:08:48.079058
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4ee7c13db44c'
down_revision: Union[str, None] = '323c95366e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wish_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('estimated_rial', sa.BigInteger(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('deadline_jalali', sa.String(length=12), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('image_name', sa.String(length=160), nullable=True),
    sa.Column('is_bought', sa.Boolean(), nullable=False),
    sa.Column('bought_jalali', sa.String(length=12), nullable=True),
    sa.Column('bought_transaction_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bought_transaction_id'], ['transaction.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wish_item_category_id'), 'wish_item', ['category_id'], unique=False)
    op.create_index(op.f('ix_wish_item_deadline_date'), 'wish_item', ['deadline_date'], unique=False)
    op.create_index(op.f('ix_wish_item_is_bought'), 'wish_item', ['is_bought'], unique=False)
    op.create_index(op.f('ix_wish_item_priority'), 'wish_item', ['priority'], unique=False)
    op.add_column('debt', sa.Column('account_id', sa.Integer(), nullable=True))
    # server_default لازم است تا روی قرض‌های موجود هم بنشیند
    op.add_column(
        'debt', sa.Column('is_cash', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.create_index(op.f('ix_debt_account_id'), 'debt', ['account_id'], unique=False)
    op.create_foreign_key(None, 'debt', 'account', ['account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'debt', type_='foreignkey')
    op.drop_index(op.f('ix_debt_account_id'), table_name='debt')
    op.drop_column('debt', 'is_cash')
    op.drop_column('debt', 'account_id')
    op.drop_index(op.f('ix_wish_item_priority'), table_name='wish_item')
    op.drop_index(op.f('ix_wish_item_is_bought'), table_name='wish_item')
    op.drop_index(op.f('ix_wish_item_deadline_date'), table_name='wish_item')
    op.drop_index(op.f('ix_wish_item_category_id'), table_name='wish_item')
    op.drop_table('wish_item')
    # ### end Alembic commands ###
