"""initial schema

Revision ID: 59da7f106ad5
Revises: 
Create Date: 2026-09-01 20:03:49.410310
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '59da7f106ad5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('account_number', sa.String(length=40), nullable=True),
    sa.Column('owner_name', sa.String(length=160), nullable=True),
    sa.Column('opened_at_jalali', sa.String(length=12), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iban')
    )
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name_fa', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    op.create_table('owner_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('value_norm', sa.String(length=200), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value', name='uq_owner_alias_kind_value')
    )
    op.create_index(op.f('ix_owner_alias_value_norm'), 'owner_alias', ['value_norm'], unique=False)
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('jalali_year', sa.Integer(), nullable=True),
    sa.Column('jalali_month', sa.Integer(), nullable=True),
    sa.Column('amount_rial', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'jalali_year', 'jalali_month', name='uq_budget_period')
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('lender', sa.String(length=160), nullable=True),
    sa.Column('loan_ref', sa.String(length=40), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('principal_rial', sa.BigInteger(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('installment_count', sa.Integer(), nullable=False),
    sa.Column('installment_amount_rial', sa.BigInteger(), nullable=False),
    sa.Column('first_due_jalali', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_loan_ref'), 'loan', ['loan_ref'], unique=False)
    op.create_table('merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fa', sa.String(length=200), nullable=False),
    sa.Column('name_norm', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_category_id'), 'merchant', ['category_id'], unique=False)
    op.create_index(op.f('ix_merchant_name_norm'), 'merchant', ['name_norm'], unique=False)
    op.create_table('statement_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('bank', sa.String(length=20), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('period_from_jalali', sa.String(length=20), nullable=True),
    sa.Column('period_to_jalali', sa.String(length=20), nullable=True),
    sa.Column('opening_balance_rial', sa.BigInteger(), nullable=True),
    sa.Column('closing_balance_rial', sa.BigInteger(), nullable=True),
    sa.Column('header_total_deposit_rial', sa.BigInteger(), nullable=True),
    sa.Column('header_total_withdraw_rial', sa.BigInteger(), nullable=True),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_duplicate', sa.Integer(), nullable=False),
    sa.Column('validation', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_import_account_id'), 'statement_import', ['account_id'], unique=False)
    op.create_index(op.f('ix_statement_import_file_sha256'), 'statement_import', ['file_sha256'], unique=False)
    op.create_table('merchant_identifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value', name='uq_identifier_kind_value')
    )
    op.create_index(op.f('ix_merchant_identifier_merchant_id'), 'merchant_identifier', ['merchant_id'], unique=False)
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('match_bank_tx_type', sa.String(length=60), nullable=True),
    sa.Column('match_description_regex', sa.Text(), nullable=True),
    sa.Column('match_counterparty_regex', sa.Text(), nullable=True),
    sa.Column('match_direction', sa.String(length=8), nullable=True),
    sa.Column('match_amount_min', sa.BigInteger(), nullable=True),
    sa.Column('match_amount_max', sa.BigInteger(), nullable=True),
    sa.Column('set_category_id', sa.Integer(), nullable=True),
    sa.Column('set_merchant_id', sa.Integer(), nullable=True),
    sa.Column('set_is_transfer', sa.Boolean(), nullable=True),
    sa.Column('set_needs_review', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['set_category_id'], ['category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['set_merchant_id'], ['merchant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_priority'), 'rule', ['priority'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('occurred_date', sa.Date(), nullable=False),
    sa.Column('jalali_datetime', sa.String(length=24), nullable=False),
    sa.Column('jalali_year', sa.Integer(), nullable=False),
    sa.Column('jalali_month', sa.Integer(), nullable=False),
    sa.Column('jalali_day', sa.Integer(), nullable=False),
    sa.Column('amount_rial', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('balance_after_rial', sa.BigInteger(), nullable=True),
    sa.Column('bank_tx_type', sa.String(length=60), nullable=True),
    sa.Column('doc_number', sa.String(length=40), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('description_norm', sa.Text(), nullable=False),
    sa.Column('counterparty_name', sa.String(length=200), nullable=True),
    sa.Column('counterparty_name_norm', sa.String(length=200), nullable=True),
    sa.Column('counterparty_iban', sa.String(length=34), nullable=True),
    sa.Column('counterparty_card', sa.String(length=20), nullable=True),
    sa.Column('counterparty_bank', sa.String(length=60), nullable=True),
    sa.Column('terminal_id', sa.String(length=24), nullable=True),
    sa.Column('terminal_kind', sa.String(length=24), nullable=True),
    sa.Column('deposit_no', sa.String(length=32), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('biller_id', sa.String(length=32), nullable=True),
    sa.Column('loan_ref', sa.String(length=32), nullable=True),
    sa.Column('trace_ref', sa.String(length=40), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('categorized_by', sa.String(length=12), nullable=False),
    sa.Column('is_self_transfer', sa.Boolean(), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_id'], ['statement_import.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'dedup_hash', name='uq_tx_account_dedup')
    )
    op.create_index(op.f('ix_transaction_amount_rial'), 'transaction', ['amount_rial'], unique=False)
    op.create_index(op.f('ix_transaction_bank_tx_type'), 'transaction', ['bank_tx_type'], unique=False)
    op.create_index(op.f('ix_transaction_biller_id'), 'transaction', ['biller_id'], unique=False)
    op.create_index(op.f('ix_transaction_category_id'), 'transaction', ['category_id'], unique=False)
    op.create_index(op.f('ix_transaction_counterparty_card'), 'transaction', ['counterparty_card'], unique=False)
    op.create_index(op.f('ix_transaction_counterparty_iban'), 'transaction', ['counterparty_iban'], unique=False)
    op.create_index(op.f('ix_transaction_counterparty_name_norm'), 'transaction', ['counterparty_name_norm'], unique=False)
    op.create_index(op.f('ix_transaction_deposit_no'), 'transaction', ['deposit_no'], unique=False)
    op.create_index(op.f('ix_transaction_direction'), 'transaction', ['direction'], unique=False)
    op.create_index(op.f('ix_transaction_doc_number'), 'transaction', ['doc_number'], unique=False)
    op.create_index(op.f('ix_transaction_is_self_transfer'), 'transaction', ['is_self_transfer'], unique=False)
    op.create_index(op.f('ix_transaction_jalali_month'), 'transaction', ['jalali_month'], unique=False)
    op.create_index(op.f('ix_transaction_jalali_year'), 'transaction', ['jalali_year'], unique=False)
    op.create_index(op.f('ix_transaction_loan_ref'), 'transaction', ['loan_ref'], unique=False)
    op.create_index(op.f('ix_transaction_merchant_id'), 'transaction', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transaction_occurred_at'), 'transaction', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_transaction_occurred_date'), 'transaction', ['occurred_date'], unique=False)
    op.create_index(op.f('ix_transaction_phone_number'), 'transaction', ['phone_number'], unique=False)
    op.create_index(op.f('ix_transaction_terminal_id'), 'transaction', ['terminal_id'], unique=False)
    op.create_index(op.f('ix_transaction_trace_ref'), 'transaction', ['trace_ref'], unique=False)
    op.create_index('ix_tx_account_occurred', 'transaction', ['account_id', 'occurred_at'], unique=False)
    op.create_index('ix_tx_review', 'transaction', ['needs_review'], unique=False)
    op.create_table('loan_installment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('due_jalali', sa.String(length=12), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_rial', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('paid_jalali', sa.String(length=12), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('paid_amount_rial', sa.BigInteger(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'seq', name='uq_installment_seq')
    )
    op.create_index(op.f('ix_loan_installment_due_date'), 'loan_installment', ['due_date'], unique=False)
    op.create_index(op.f('ix_loan_installment_loan_id'), 'loan_installment', ['loan_id'], unique=False)
    op.create_index(op.f('ix_loan_installment_status'), 'loan_installment', ['status'], unique=False)
    op.create_table('loan_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.Integer(), nullable=True),
    sa.Column('stored_name', sa.String(length=160), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installment_id'], ['loan_installment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_attachment_installment_id'), 'loan_attachment', ['installment_id'], unique=False)
    op.create_index(op.f('ix_loan_attachment_loan_id'), 'loan_attachment', ['loan_id'], unique=False)
    op.create_index(op.f('ix_loan_attachment_sha256'), 'loan_attachment', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_attachment_sha256'), table_name='loan_attachment')
    op.drop_index(op.f('ix_loan_attachment_loan_id'), table_name='loan_attachment')
    op.drop_index(op.f('ix_loan_attachment_installment_id'), table_name='loan_attachment')
    op.drop_table('loan_attachment')
    op.drop_index(op.f('ix_loan_installment_status'), table_name='loan_installment')
    op.drop_index(op.f('ix_loan_installment_loan_id'), table_name='loan_installment')
    op.drop_index(op.f('ix_loan_installment_due_date'), table_name='loan_installment')
    op.drop_table('loan_installment')
    op.drop_index('ix_tx_review', table_name='transaction')
    op.drop_index('ix_tx_account_occurred', table_name='transaction')
    op.drop_index(op.f('ix_transaction_trace_ref'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_terminal_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_phone_number'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_occurred_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_occurred_at'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_merchant_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_loan_ref'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_jalali_year'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_jalali_month'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_is_self_transfer'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_doc_number'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_direction'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_deposit_no'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_counterparty_name_norm'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_counterparty_iban'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_counterparty_card'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_category_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_biller_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_bank_tx_type'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_amount_rial'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_rule_priority'), table_name='rule')
    op.drop_table('rule')
    op.drop_index(op.f('ix_merchant_identifier_merchant_id'), table_name='merchant_identifier')
    op.drop_table('merchant_identifier')
    op.drop_index(op.f('ix_statement_import_file_sha256'), table_name='statement_import')
    op.drop_index(op.f('ix_statement_import_account_id'), table_name='statement_import')
    op.drop_table('statement_import')
    op.drop_index(op.f('ix_merchant_name_norm'), table_name='merchant')
    op.drop_index(op.f('ix_merchant_category_id'), table_name='merchant')
    op.drop_table('merchant')
    op.drop_index(op.f('ix_loan_loan_ref'), table_name='loan')
    op.drop_table('loan')
    op.drop_table('budget')
    op.drop_index(op.f('ix_owner_alias_value_norm'), table_name='owner_alias')
    op.drop_table('owner_alias')
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    op.drop_table('category')
    op.drop_table('app_setting')
    op.drop_table('account')
    # ### end Alembic commands ###
