"""market prices and asset holdings

Revision ID: 60d4bc6f0d38
Revises: 0e834d77d779
Create Date: 2026-09-02 16:19:59.745083
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '60d4bc6f0d38'
down_revision: Union[str, None] = '0e834d77d779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('endpoint', sa.String(length=40), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_call_log_called_at'), 'api_call_log', ['called_at'], unique=False)
    op.create_index(op.f('ix_api_call_log_provider'), 'api_call_log', ['provider'], unique=False)
    op.create_table('market_item',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label_fa', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('unit_fa', sa.String(length=40), nullable=False),
    sa.Column('is_tracked', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('price_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=40), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('jalali_date', sa.String(length=12), nullable=False),
    sa.Column('open_rial', sa.BigInteger(), nullable=True),
    sa.Column('high_rial', sa.BigInteger(), nullable=True),
    sa.Column('low_rial', sa.BigInteger(), nullable=True),
    sa.Column('close_rial', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_code'], ['market_item.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_code', 'price_date', name='uq_price_item_date')
    )
    op.create_index(op.f('ix_price_point_item_code'), 'price_point', ['item_code'], unique=False)
    op.create_index(op.f('ix_price_point_price_date'), 'price_point', ['price_date'], unique=False)
    op.create_table('asset_holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('acquired_jalali', sa.String(length=12), nullable=False),
    sa.Column('acquired_date', sa.Date(), nullable=False),
    sa.Column('cost_rial', sa.BigInteger(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_code'], ['market_item.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_holding_acquired_date'), 'asset_holding', ['acquired_date'], unique=False)
    op.create_index(op.f('ix_asset_holding_item_code'), 'asset_holding', ['item_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_holding_item_code'), table_name='asset_holding')
    op.drop_index(op.f('ix_asset_holding_acquired_date'), table_name='asset_holding')
    op.drop_table('asset_holding')
    op.drop_index(op.f('ix_price_point_price_date'), table_name='price_point')
    op.drop_index(op.f('ix_price_point_item_code'), table_name='price_point')
    op.drop_table('price_point')
    op.drop_table('market_item')
    op.drop_index(op.f('ix_api_call_log_provider'), table_name='api_call_log')
    op.drop_index(op.f('ix_api_call_log_called_at'), table_name='api_call_log')
    op.drop_table('api_call_log')
    # ### end Alembic commands ###
